name: Build and deploy app to Azure Container Registry

on:
  workflow_dispatch:
  
env:
  APP_PATH: './src/Web'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ${{env.APP_PATH}} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{env.APP_PATH}} -c Release -o ${{env.APP_PATH}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.APP_PATH}}/myapp

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: release
      
      - name: Run
        run: |
          pwd
