name: Create a GitHub Self-Hosted runner container

on:
  workflow_dispatch:
    inputs:
      deploy-aci:
        description: 'Azure Container Instances の展開有無'
        required: true
        type: boolean
      resourceGroup:
        description: 'Resource Group 名'
        required: false
        type: string
      virtualNetwork:
        description: '仮想ネットワーク名'
        required: false
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "build and push image- ${{ github.sha }}"

  deploy-new-aci:
    if: ${{ github.event.inputs.deploy-aci == 'true' }}
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    steps:
      - name: Azure CLI script
        uses: azure/CLI@v1
        inlineScript: |
          az network vnet show -g ${{ github.event.inputs.resourceGroup }} -n ${{ github.event.inputs.virtualNetwork }}