name: Trigger auto deployment for ca-devops-test1

# When this action will be executed
on:
  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: crworkshop1.azurecr.io
          username: ${{ secrets.CADEVOPSTEST1_REGISTRY_USERNAME }}
          password: ${{ secrets.CADEVOPSTEST1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crworkshop1.azurecr.io/dotnet-app:${{ github.sha }}
          file: ./dockerfiles/app/dockerfile/Dockerfile
          context: ./dockerfiles/app/dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CADEVOPSTEST1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-devops-test1 -g rg-Pre-Workshop --server crworkshop1.azurecr.io --username  ${{ secrets.CADEVOPSTEST1_REGISTRY_USERNAME }} --password ${{ secrets.CADEVOPSTEST1_REGISTRY_PASSWORD }}
            az containerapp update -n ca-devops-test1 -g rg-Pre-Workshop --image crworkshop1.azurecr.io/dotnet-app:${{ github.sha }}
